package cn.vie.vibe.gallery.api;
import cn.vie.vibe.gallery.application.*; import cn.vie.vibe.gallery.domain.*; import jakarta.validation.constraints.Size; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.IOException; import java.net.URI; import java.util.*; import java.time.Instant;
@RestController @RequestMapping("/api") public class PhotoController { private final PhotoFacade facade; private final StorageObjectRepository objects; private final ObjectStoragePort storage; private final TenantContextResolver context; public PhotoController(PhotoFacade f,StorageObjectRepository o,ObjectStoragePort s,TenantContextResolver c){facade=f;objects=o;storage=s;context=c;}
 @PostMapping(value="/galleries/{galleryId}/photos",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<UploadResponse> upload(@PathVariable UUID galleryId,@RequestParam("files") List<MultipartFile> files) throws IOException { if(files==null||files.isEmpty()||files.size()>50) throw new DomainException("FILE_INVALID","At least one and at most 50 files are required"); List<PhotoFacade.UploadResult> r=new ArrayList<>(); for(MultipartFile f:files) r.add(facade.upload(galleryId,new PhotoUpload(f.getOriginalFilename(),f.getContentType(),f.getSize(),f.getInputStream()))); return ResponseEntity.status(HttpStatus.ACCEPTED).body(new UploadResponse(r)); }
 @GetMapping("/galleries/{galleryId}/photos") public List<PhotoResponse> list(@PathVariable UUID galleryId){UUID tenant=context.requireContext().tenantId();return facade.list(galleryId).stream().map(p->{var o=objects.findById(tenant,p.storageObjectId()).orElse(null);String url=o!=null&&o.thumbnailKey()!=null&&o.status()==StorageObjectStatus.READY?storage.createReadUrl(o.thumbnailKey()).toString():null;return PhotoResponse.from(p,o,url);}).toList();}
 @PatchMapping("/photos/{photoId}") public PhotoResponse update(@PathVariable UUID photoId,@RequestBody UpdateRequest request){return PhotoResponse.from(facade.update(photoId,request.title(),request.sortOrder(),request.cover()),null,null);}
 @DeleteMapping("/photos/{photoId}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable UUID photoId){facade.delete(photoId);}
 public record UploadResponse(List<PhotoFacade.UploadResult> items){} public record UpdateRequest(String title,Integer sortOrder,Boolean cover){} public record PhotoResponse(String id,String galleryId,String title,int sortOrder,boolean cover,PhotoStatus status,Instant createdAt,long byteSize,Integer width,Integer height,String thumbnailUrl){static PhotoResponse from(Photo p,StorageObject o,String url){return new PhotoResponse(p.id().toString(),p.galleryId().toString(),p.title(),p.sortOrder(),p.cover(),p.status(),p.createdAt(),o==null?0:o.byteSize(),o==null?null:o.width(),o==null?null:o.height(),url);}}
}
