package cn.vie.vibe.gallery.infrastructure;
import cn.vie.vibe.gallery.application.*; import cn.vie.vibe.gallery.domain.*; import org.springframework.context.annotation.Profile; import org.springframework.stereotype.Component; import java.util.*; import java.util.concurrent.ConcurrentHashMap;
@Profile("dev-memory")
@Component class DevGalleryLookup implements GalleryLookup { public Optional<Gallery> findById(UUID t,UUID g){return Optional.of(new Gallery(g,t,"dev","Dev",GalleryVisibility.PRIVATE,null,null,false,java.time.Instant.now()));} }
@Profile("dev-memory") @Component class DevPhotoRepository implements PhotoRepository { final Map<UUID,Photo> m=new ConcurrentHashMap<>(); public Photo save(Photo p){m.put(p.id(),p);return p;} public List<Photo> findByGallery(UUID t,UUID g){return m.values().stream().filter(p->p.tenantId().equals(t)&&p.galleryId().equals(g)&&p.status()!=PhotoStatus.DELETED).toList();} public List<Photo> findByGalleryIdWithPagination(UUID g,int o,int l){return m.values().stream().filter(p->p.galleryId().equals(g)&&p.status()!=PhotoStatus.DELETED).skip(o).limit(l).toList();} public int countByGalleryId(UUID g){return (int)m.values().stream().filter(p->p.galleryId().equals(g)&&p.status()!=PhotoStatus.DELETED).count();} public Optional<Photo> findById(UUID t,UUID id){return Optional.ofNullable(m.get(id)).filter(p->p.tenantId().equals(t)&&p.status()!=PhotoStatus.DELETED);} public Optional<Photo> findById(UUID id){return Optional.ofNullable(m.get(id)).filter(p->p.status()!=PhotoStatus.DELETED);} public int updateStatus(UUID t,UUID id,PhotoStatus s){return findById(t,id).map(p->{m.put(id,new Photo(p.id(),p.tenantId(),p.galleryId(),p.storageObjectId(),p.title(),p.sortOrder(),p.cover(),s,p.createdAt()));return 1;}).orElse(0);} public int updateMetadata(UUID t,UUID id,String a,Integer b,Boolean c){return findById(t,id).map(p->{m.put(id,new Photo(p.id(),p.tenantId(),p.galleryId(),p.storageObjectId(),a==null?p.title():a,b==null?p.sortOrder():b,c==null?p.cover():c,p.status(),p.createdAt()));return 1;}).orElse(0);} public int clearCoverByGallery(UUID t,UUID g){m.values().stream().filter(p->p.tenantId().equals(t)&&p.galleryId().equals(g)&&p.cover()).forEach(p->m.put(p.id(),new Photo(p.id(),p.tenantId(),p.galleryId(),p.storageObjectId(),p.title(),p.sortOrder(),false,p.status(),p.createdAt())));return 1;} public int softDelete(UUID t,UUID id){return updateStatus(t,id,PhotoStatus.DELETED);} }
@Profile("dev-memory") @Component class DevStorageObjectRepository implements StorageObjectRepository { final Map<UUID,StorageObject> m=new ConcurrentHashMap<>(); public StorageObject save(StorageObject x){m.put(x.id(),x);return x;} public Optional<StorageObject> findById(UUID t,UUID i){return Optional.ofNullable(m.get(i));} public int markReady(UUID t,UUID i,String k,Integer w,Integer h){return 1;} public int markFailed(UUID t,UUID i){return 1;} public int softDelete(UUID t,UUID i){return 1;} }
@Profile("dev-memory") @Component class DevTaskRepository implements PhotoProcessingTaskRepository { final Map<UUID,PhotoProcessingTask> m=new ConcurrentHashMap<>(); public PhotoProcessingTask save(PhotoProcessingTask t){m.put(t.id(),t);return t;} public Optional<PhotoProcessingTask> findById(UUID t,UUID i){return Optional.ofNullable(m.get(i));} public Optional<PhotoProcessingTask> claimNext(){return m.values().stream().filter(x->x.status()==TaskStatus.PENDING).findFirst();} public int succeed(UUID i){return 1;} public int fail(UUID i,String e,boolean t){return 1;} }
@Profile("dev-memory") @Component class DevQuotaRepository implements TenantQuotaRepository { final Map<UUID,TenantQuota> m=new ConcurrentHashMap<>(); public TenantQuota findForUpdate(UUID t){return m.getOrDefault(t,new TenantQuota(t,5L*1024*1024*1024,0,10000,0));} public void ensure(UUID t,long b,long p){m.putIfAbsent(t,new TenantQuota(t,b,0,p,0));} public synchronized void reserve(UUID t,long b,long p){TenantQuota q=findForUpdate(t);if(q.usedBytes()+b>q.maxBytes()||q.photoCount()+p>q.maxPhotos())throw new DomainException("QUOTA_EXCEEDED","Quota exceeded");m.put(t,new TenantQuota(t,q.maxBytes(),q.usedBytes()+b,q.maxPhotos(),q.photoCount()+p));} public synchronized void release(UUID t,long b,long p){TenantQuota q=findForUpdate(t);m.put(t,new TenantQuota(t,q.maxBytes(),Math.max(0,q.usedBytes()-b),q.maxPhotos(),Math.max(0,q.photoCount()-p)));} }
@Profile("dev-memory") @Component class DevGalleryViewerConfigRepository implements GalleryViewerConfigRepository { final Map<UUID,GalleryViewerConfig> m=new ConcurrentHashMap<>(); public Optional<GalleryViewerConfig> findByGalleryId(UUID g){return Optional.ofNullable(m.get(g));} public void save(GalleryViewerConfig c){m.put(c.galleryId(),c);} public int deleteByGalleryId(UUID g){return m.remove(g)!=null?1:0;} }
