package cn.vie.vibe.gallery.infrastructure.persistence.mapper;
import org.apache.ibatis.annotations.*; import java.util.*;
@Mapper public interface TaskQuotaMapper {
 @Insert("INSERT INTO photo_processing_task(id,tenant_id,photo_id,status,attempts,created_at,updated_at) VALUES(UUID_TO_BIN(#{id}),UUID_TO_BIN(#{tenant}),UUID_TO_BIN(#{photo}),#{status},0,#{at},#{at})") int task(@Param("id")String i,@Param("tenant")String t,@Param("photo")String p,@Param("status")String s,@Param("at")java.time.LocalDateTime at);
 @Select("SELECT BIN_TO_UUID(id) id,BIN_TO_UUID(tenant_id) tenantId,BIN_TO_UUID(photo_id) photoId,status,attempts,error_message errorMessage,locked_at lockedAt,completed_at completedAt FROM photo_processing_task WHERE tenant_id=UUID_TO_BIN(#{tenant}) AND id=UUID_TO_BIN(#{id})") Map<String,Object> taskById(@Param("tenant")String t,@Param("id")String i);
 @Select("SELECT BIN_TO_UUID(id) id,BIN_TO_UUID(tenant_id) tenantId,BIN_TO_UUID(photo_id) photoId,status,attempts,error_message errorMessage,locked_at lockedAt,completed_at completedAt FROM photo_processing_task WHERE status='PENDING' OR (status='PROCESSING' AND locked_at < UTC_TIMESTAMP(6)-INTERVAL 10 MINUTE) ORDER BY created_at LIMIT 1") Map<String,Object> nextTask();
 @Update("UPDATE photo_processing_task SET status='PROCESSING',locked_at=UTC_TIMESTAMP(6),updated_at=UTC_TIMESTAMP(6) WHERE id=UUID_TO_BIN(#{id}) AND (status='PENDING' OR (status='PROCESSING' AND locked_at < UTC_TIMESTAMP(6)-INTERVAL 10 MINUTE))") int claim(@Param("id")String i);
 @Update("UPDATE photo_processing_task SET status='SUCCEEDED',completed_at=UTC_TIMESTAMP(6),updated_at=UTC_TIMESTAMP(6) WHERE id=UUID_TO_BIN(#{id}) AND status='PROCESSING'") int succeed(@Param("id")String i);
 @Update("UPDATE photo_processing_task SET attempts=attempts+1,status=#{status},error_message=#{error},updated_at=UTC_TIMESTAMP(6) WHERE id=UUID_TO_BIN(#{id})") int fail(@Param("id")String i,@Param("status")String s,@Param("error")String e);
 @Insert("INSERT INTO tenant_quota(tenant_id,max_bytes,max_photos) VALUES(UUID_TO_BIN(#{tenant}),#{maxBytes},#{maxPhotos}) ON DUPLICATE KEY UPDATE tenant_id=tenant_id") int ensure(@Param("tenant")String t,@Param("maxBytes")long b,@Param("maxPhotos")long p);
 @Select("SELECT BIN_TO_UUID(tenant_id) tenantId,max_bytes maxBytes,used_bytes usedBytes,max_photos maxPhotos,photo_count photoCount FROM tenant_quota WHERE tenant_id=UUID_TO_BIN(#{tenant}) FOR UPDATE") Map<String,Object> quota(@Param("tenant")String t);
 @Update("UPDATE tenant_quota SET used_bytes=used_bytes+#{bytes},photo_count=photo_count+#{photos} WHERE tenant_id=UUID_TO_BIN(#{tenant}) AND used_bytes+#{bytes}<=max_bytes AND photo_count+#{photos}<=max_photos") int reserve(@Param("tenant")String t,@Param("bytes")long b,@Param("photos")long p);
 @Update("UPDATE tenant_quota SET used_bytes=GREATEST(0,used_bytes-#{bytes}),photo_count=GREATEST(0,photo_count-#{photos}) WHERE tenant_id=UUID_TO_BIN(#{tenant})") int release(@Param("tenant")String t,@Param("bytes")long b,@Param("photos")long p);
}
